name: Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
    version:
      description: 'Version to deploy'
      required: true
      type: string
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, linux, deploy]
    environment: production

    steps:
      - name: download release
        id: download_release
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.whl'
      - name: copy release file
        run: |
          tmpfile=$(mktemp)
          echo "${{ secrets.KEY }}" > ${tmpfile}
          scp -i ${tmpfile} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "${{ fromJson(steps.download_release.outputs.downloaded_files)[0] }}" "${{ vars.USER }}@${{ vars.HOST }}:/gritadm/guam/releases/"
      - name: install release
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.KEY }}
          script: |
            FILENAME="$(basename '${{ fromJson(steps.download_release.outputs.downloaded_files)[0] }}')"
            /gritadm/guam_venv/bin/pip install ~/guam/releases/$FILENAME
      - name: restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.KEY }}
          script: |
            sudo systemctl restart guam.service
